# SPDX-FileCopyrightText: 2025 EvoCloud, Inc.
# SPDX-License-Identifier: MPL-2.0
# Source: https://github.com/kubernetes-sigs/karpenter-provider-cluster-api
# Reference: https://github.com/kubernetes-sigs/karpenter-provider-cluster-api/blob/main/Makefile
# Schema: https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md

package:
  name: karpenter-provider-cluster-api
  version: 0.2.0
  epoch: 0
  description: "An implementation of Karpenter that uses Cluster API as the infrastructure provider."
  target-architecture:
    - x86_64
  copyright:
    - attestation: |
        Created by the EvoCloud Engineering Team.
        Copyright (C) 2025 EvoCloud, Inc.
      license: MPL-2.0
  url: "https://github.com/kubernetes-sigs/karpenter-provider-cluster-api"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle
vars:
  git_commit: "9be2dd2dafc7b57e6bb3a8341e650a04145c3e1d"
  
pipeline:
  #https://github.com/chainguard-dev/melange/blob/main/pkg/build/pipelines/git-checkout.yaml
  - name: "DOWNLOADING KARPENTER-PROVIDER-CLUSTER-API SOURCE CODE"
    uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/karpenter-provider-cluster-api
      expected-commit: ${{vars.git_commit}}
      tag: v${{package.version}}

 
  - name: "BUILD KARPENTER-CLUSTER-API-CONTROLLER BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./cmd/controller
      ldflags: -s 
      output:  karpenter-clusterapi-controller

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/karpenter-provider-cluster-api
    strip-prefix: v