# SPDX-FileCopyrightText: 2025 EvoCloud, Inc.
# SPDX-License-Identifier: MPL-2.0

# Source: https://github.com/karmada-io/karmada
# Reference: https://github.com/karmada-io/karmada/blob/master/hack/util.sh
# Schema: https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md

package:
  name: karmada
  version: 1.16.0
  epoch: 1
  description: "Open, Multi-Cloud, Multi-Cluster Kubernetes Orchestration"
  target-architecture:
    - x86_64
  copyright:
    - attestation: |
        Created by the EvoCloud Engineering Team.
        Copyright (C) 2025 EvoCloud, Inc.
      license: MPL-2.0
  url: "https://github.com/karmada-io/karmada"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle

vars:
  git_commit: "b1ff49568525b6bff36869af7dc3beb2add92425"
  build_date: "2025-12-24T09:37:22Z"
  git_major: "1"
  git_minor: "16"

pipeline:
  #https://github.com/chainguard-dev/melange/blob/main/pkg/build/pipelines/git-checkout.yaml
  - name: "DOWNLOADING KARMADA SOURCE CODE"
    uses: git-checkout
    with:
      repository: https://github.com/karmada-io/karmada
      expected-commit: ${{vars.git_commit}}
      tag: v${{package.version}}

  - name: "PATCHING GO MODULES"
    # secfixes:
    #   1.16.0-r1:
    #     - GHSA-j5w8-q4qc-rx2x
    #     - GHSA-f6x5-jh6r-wrfv
    runs: |
      go get golang.org/x/crypto@v0.45.0
      go mod tidy
      go mod vendor
      
  - name: "BUILD KARMADA-AGGREGATED-API-SERVER BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./cmd/aggregated-apiserver 
      ldflags: |
        -s 
        -X github.com/karmada-io/karmada/pkg/version.gitVersion=${{package.version}}
        -X github.com/karmada-io/karmada/pkg/version.gitCommit=${{vars.git_commit}}
        -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean
        -X github.com/karmada-io/karmada/pkg/version.gitShortCommit=${{vars.git_commit}} 
        -X github.com/karmada-io/karmada/pkg/version.buildDate=${{vars.build_date}}
      output: karmada-aggregated-apiserver

  - name: "BUILD KARMADA-CONTROLLER-MANAGER BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./cmd/controller-manager
      ldflags: |
        -s 
        -X github.com/karmada-io/karmada/pkg/version.gitVersion=${{package.version}}
        -X github.com/karmada-io/karmada/pkg/version.gitCommit=${{vars.git_commit}}
        -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean
        -X github.com/karmada-io/karmada/pkg/version.gitShortCommit=${{vars.git_commit}} 
        -X github.com/karmada-io/karmada/pkg/version.buildDate=${{vars.build_date}}
      output: karmada-controller-manager

  - name: "BUILD KARMADA-SCHEDULER BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./cmd/scheduler 
      ldflags: |
        -s 
        -X github.com/karmada-io/karmada/pkg/version.gitVersion=${{package.version}}
        -X github.com/karmada-io/karmada/pkg/version.gitCommit=${{vars.git_commit}}
        -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean
        -X github.com/karmada-io/karmada/pkg/version.gitShortCommit=${{vars.git_commit}} 
        -X github.com/karmada-io/karmada/pkg/version.buildDate=${{vars.build_date}}
      output: karmada-scheduler 
  
  - name: "BUILD KARMADA-DESCHEDULER BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./cmd/descheduler 
      ldflags: |
        -s 
        -X github.com/karmada-io/karmada/pkg/version.gitVersion=${{package.version}}
        -X github.com/karmada-io/karmada/pkg/version.gitCommit=${{vars.git_commit}}
        -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean
        -X github.com/karmada-io/karmada/pkg/version.gitShortCommit=${{vars.git_commit}} 
        -X github.com/karmada-io/karmada/pkg/version.buildDate=${{vars.build_date}}
      output: karmada-descheduler

  - name: "BUILD KARMADA-WEBHOOK BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./cmd/webhook
      ldflags: |
        -s 
        -X github.com/karmada-io/karmada/pkg/version.gitVersion=${{package.version}}
        -X github.com/karmada-io/karmada/pkg/version.gitCommit=${{vars.git_commit}}
        -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean
        -X github.com/karmada-io/karmada/pkg/version.gitShortCommit=${{vars.git_commit}} 
        -X github.com/karmada-io/karmada/pkg/version.buildDate=${{vars.build_date}}
      output: karmada-webhook

  - name: "BUILD KARMADA-AGENT BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./cmd/agent
      ldflags: |
        -s 
        -X github.com/karmada-io/karmada/pkg/version.gitVersion=${{package.version}}
        -X github.com/karmada-io/karmada/pkg/version.gitCommit=${{vars.git_commit}}
        -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean
        -X github.com/karmada-io/karmada/pkg/version.gitShortCommit=${{vars.git_commit}} 
        -X github.com/karmada-io/karmada/pkg/version.buildDate=${{vars.build_date}}
      output: karmada-agent

  - name: "BUILD KARMADA-SCHEDULER-ESTIMATOR BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./cmd/scheduler-estimator 
      ldflags: |
        -s 
        -X github.com/karmada-io/karmada/pkg/version.gitVersion=${{package.version}}
        -X github.com/karmada-io/karmada/pkg/version.gitCommit=${{vars.git_commit}}
        -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean
        -X github.com/karmada-io/karmada/pkg/version.gitShortCommit=${{vars.git_commit}} 
        -X github.com/karmada-io/karmada/pkg/version.buildDate=${{vars.build_date}}
      output: karmada-scheduler-estimator

  - name: "BUILD KARMADA-INTERPRETER-WEBHOOK-EXAMPLE BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./examples/customresourceinterpreter/webhook

      ldflags: |
        -s 
        -X github.com/karmada-io/karmada/pkg/version.gitVersion=${{package.version}}
        -X github.com/karmada-io/karmada/pkg/version.gitCommit=${{vars.git_commit}}
        -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean
        -X github.com/karmada-io/karmada/pkg/version.gitShortCommit=${{vars.git_commit}} 
        -X github.com/karmada-io/karmada/pkg/version.buildDate=${{vars.build_date}}
      output: karmada-interpreter-webhook-example

  
  - name: "BUILD KARMADA-SEARCH BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./cmd/karmada-search 
      ldflags: |
        -s 
        -X github.com/karmada-io/karmada/pkg/version.gitVersion=${{package.version}}
        -X github.com/karmada-io/karmada/pkg/version.gitCommit=${{vars.git_commit}}
        -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean
        -X github.com/karmada-io/karmada/pkg/version.gitShortCommit=${{vars.git_commit}} 
        -X github.com/karmada-io/karmada/pkg/version.buildDate=${{vars.build_date}}
      output: karmada-search 

  - name: "BUILD KARMADA-OPERATOR BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./operator/cmd/operator
      ldflags: |
        -s 
        -X github.com/karmada-io/karmada/pkg/version.gitVersion=${{package.version}}
        -X github.com/karmada-io/karmada/pkg/version.gitCommit=${{vars.git_commit}}
        -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean
        -X github.com/karmada-io/karmada/pkg/version.gitShortCommit=${{vars.git_commit}} 
        -X github.com/karmada-io/karmada/pkg/version.buildDate=${{vars.build_date}}
      output: karmada-operator

  - name: "BUILD KARMADA-METRICS-ADAPTER BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./cmd/metrics-adapter 
      ldflags: |
        -s 
        -X github.com/karmada-io/karmada/pkg/version.gitVersion=${{package.version}}
        -X github.com/karmada-io/karmada/pkg/version.gitCommit=${{vars.git_commit}}
        -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean
        -X github.com/karmada-io/karmada/pkg/version.gitShortCommit=${{vars.git_commit}} 
        -X github.com/karmada-io/karmada/pkg/version.buildDate=${{vars.build_date}}
      output: karmada-metrics-adapter

  - name: "BUILD KUBECTL-KARMADA BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./cmd/kubectl-karmada
      ldflags: |
        -s 
        -X github.com/karmada-io/karmada/pkg/version.gitVersion=${{package.version}}
        -X github.com/karmada-io/karmada/pkg/version.gitCommit=${{vars.git_commit}}
        -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean
        -X github.com/karmada-io/karmada/pkg/version.gitShortCommit=${{vars.git_commit}} 
        -X github.com/karmada-io/karmada/pkg/version.buildDate=${{vars.build_date}}
      output: kubectl-karmada

  - name: "BUILD KARMADACTL BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./cmd/karmadactl
      ldflags: |
        -s 
        -X github.com/karmada-io/karmada/pkg/version.gitVersion=${{package.version}}
        -X github.com/karmada-io/karmada/pkg/version.gitCommit=${{vars.git_commit}}
        -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean
        -X github.com/karmada-io/karmada/pkg/version.gitShortCommit=${{vars.git_commit}} 
        -X github.com/karmada-io/karmada/pkg/version.buildDate=${{vars.build_date}}
      output: karmadactl

  - uses: strip


update:
  enabled: true
  github:
    identifier: karmada-io/karmada
    strip-prefix: v  