# SPDX-License-Identifier: Apache-2.0

# Source: https://github.com/openkruise/kruise
# Schema: https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md

package:
  name: slimtoolkit-all-in-one
  version: 1.40.11
  epoch: 1
  description: "Slim(toolkit): Don't change anything in your container image and minify it by up to 30x (and for compiled languages even more) making it secure too! (free and open source)."
  target-architecture:
    - x86_64 #supported architectures: 386, amd64, arm/v6, arm/v7, arm64, ppc64le, s390x, x86_64, aarch64, and all that builds it for all of them
  copyright:
    - attestation: |
        Created by the EvoCloud Engineering Team. 
        Copyright (C) 2025 EvoCloud, Inc.
      license: MPL-2.0
  url: "https://github.com/slimtoolkit/slim"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle
      # - busybox
      # - go
      # - git
      # - make

pipeline:
  - name: "Prepare extraction directory"
    runs: |
      mkdir -p slim

  - name: "Download Slimtoolkit source"
    uses: fetch
    with:
      uri: https://github.com/slimtoolkit/slim/archive/refs/tags/${{package.version}}.tar.gz
      expected-sha512: fa1049c68b3849d51dc58b1f84797048c6fa3d75b6e49715118107bfc6700e1d8fbad0c1ff0f654ce5aa5ac216200248fa883d4482978a7ab6dbd180d2696eb7 
      directory: slim
      delete: true


  - name: "Build Slim"
    uses: go/build
    with:
      modroot: slim
      packages: ./cmd/slim
      ldflags: |
           -s
           -X github.com/slimtoolkit/slim/pkg/version.appVersionTag=${{package.version}}
           -X github.com/slimtoolkit/slim/pkg/version.appVersionRev={{.Commit}}
           -X github.com/slimtoolkit/slim/pkg/version.appVersionTime={{.Date}}
      tags: appbom_noembed   # disable gobinhash embed
      output: slim


  - name: "Build Slim-sensor"
    uses: go/build
    with:
      modroot: slim
      packages: ./cmd/slim-sensor
      ldflags: |
           -s
           -X github.com/slimtoolkit/slim/pkg/version.appVersionTag=${{package.version}}
           -X github.com/slimtoolkit/slim/pkg/version.appVersionRev={{.Commit}}
           -X github.com/slimtoolkit/slim/pkg/version.appVersionTime={{.Date}}
      tags: appbom_noembed   # disable gobinhash embed
      output: slim-sensor


  - uses: strip

  - name: "Cleanup"
    runs: |
      rm -rf slim

