# SPDX-FileCopyrightText: 2026 EvoCloud, Inc.
# SPDX-License-Identifier: MPL-2.0

# Source: https://github.com/tektoncd/chains
# Reference: https://github.com/tektoncd/chains/blob/main/Makefile
# Schema: https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md

package:
  name: chains
  version: 0.26.0
  epoch: 1
  description: "Supply Chain Security in Tekton Pipelines."
  target-architecture:
    - x86_64
  copyright:
    - attestation: |
        Created by the EvoCloud Engineering Team.
        Copyright (C) 2026 EvoCloud, Inc.
      license: MPL-2.0
  url: "https://github.com/tektoncd/chains"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle

vars:
  git_commit: "0c9284f740d672930274efbe75033df55dc78515"

pipeline:
  #https://github.com/chainguard-dev/melange/blob/main/pkg/build/pipelines/git-checkout.yaml
  - name: "DOWNLOADING TEKTONCD CHAINS SOURCE CODE"
    uses: git-checkout
    with:
      repository: https://github.com/tektoncd/chains
      expected-commit: ${{vars.git_commit}}
      tag: v${{package.version}}

  - name: "BUILD CHAINS BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./cmd/controller
      # secfixes:
      #   0.26.0-r1:
      #     - GHSA-f6x5-jh6r-wrfv
      #     - GHSA-j5w8-q4qc-rx2x 
      #     - GHSA-f83f-xpx7-ffpw
      #     - GHSA-4qg8-fj49-pxjh 
      #     - GHSA-59jp-pj84-45mr
      #     - GHSA-whqx-f9j3-ch6m 
      deps: golang.org/x/crypto@v0.45.0
      ldflags: -s 
      output: chains

  - uses: strip

update:
  enabled: true
  github:
    identifier: tektoncd/chains
    strip-prefix: v  