# SPDX-FileCopyrightText: 2025 EvoCloud, Inc.
# SPDX-License-Identifier: MPL-2.0
# Source: https://github.com/flux-iac/tofu-controller
# Reference: https://github.com/flux-iac/tofu-controller/blob/main/Makefile
# Schema: https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md

package:
  name: manager
  version:  0.16.0
  epoch: 1
  description: "A GitOps OpenTofu and Terraform controller for Flux"
  target-architecture:
    - x86_64
  copyright:
    - attestation: |
        Created by the EvoCloud Engineering Team.
        Copyright (C) 2025 EvoCloud, Inc.
      license: MPL-2.0
  url: "https://github.com/flux-iac/tofu-controller"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle

vars:
  git_commit: "b79c34726a1604abaea728aac047d81407b0162b"

pipeline:
  #https://github.com/chainguard-dev/melange/blob/main/pkg/build/pipelines/git-checkout.yaml
  - name: "DOWNLOADING TOFU-CONTROLLER SOURCE CODE"
    uses: git-checkout
    with:
      repository: https://github.com/flux-iac/tofu-controller
      expected-commit: ${{vars.git_commit}}
      tag: v${{package.version}}-rc.7

  - name: "PATCHING GO MODULES"
    # secfixes:
    #   O.16.0-r1:
    #     - GHSA-j5w8-q4qc-rx2x
    #     - GHSA-f6x5-jh6r-wrfv
    runs: |
      go get golang.org/x/crypto@v0.45.0
      go mod tidy
      go mod vendor

  - name: "BUILD MANAGER BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./cmd/manager
      ldflags: |
        -s 
        -X main.BuildSHA=${{vars.git_commit}}
        -X main.BuildVersion=${{package.version}}
      output: manager

  - uses: strip

update:
  enabled: true
  github:
    identifier: tofu-controller/tofu-controller
    strip-prefix: v