# SPDX-License-Identifier: Apache-2.0
# Source: https://github.com/kyverno/kyverno
# Schema: https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md
# Reference: https://github.com/kyverno/kyverno/blob/main/Makefile

package:
  name: kyverno-all-in-one
  version: 1.16.0
  epoch: 0
  description: "Kyverno: Kubernetes Native Policy Management"
  target-architecture:
    - x86_64
  copyright:
    - attestation: |
        Created by the EvoCloud Engineering Team.
        Copyright (C) 2025 EvoCloud, Inc.
      license: Apache-2.0
  url: "https://github.com/kyverno/kyverno"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle
      # - go
      # - git
      # - make


pipeline:
  - name: "Prepare extraction directory"
    runs: |
      mkdir -p kyverno


  - name: "Download Kyverno source"
    uses: fetch
    with:
      uri: https://github.com/kyverno/kyverno/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha512: 2c57c73de8b85c3ec80fd8568b83250214069489b7dc7437418f39c29866dd5e9c928ff2be15b65fd4f0f00b8002e9288946dfee9efbb5f62cdc97adc0de8042
      directory: kyverno
      delete: true


  - name: "Build Kyverno"
    uses: go/build
    with:
      modroot: kyverno
      packages: ./cmd/kyverno
      ldflags: |
        -s -w -X github.com/kyverno/kyverno/pkg/version.BuildVersion=${{package.version}}
        -X github.com/kyverno/kyverno/pkg/version.GitCommit={{.Commit}}
      output: kyverno


  - name: "Build Kyverno-init"
    uses: go/build
    with:
      modroot: kyverno
      packages: ./cmd/kyverno-init
      deps: golang.org/x/crypto@v0.45.0
      ldflags: |
        -s -X github.com/kyverno/kyverno/pkg/version.BuildVersion=${{package.version}}
        -X github.com/kyverno/kyverno/pkg/version.GitCommit={{.Commit}}
      output: kyverno-init


  - name: "Build Kubectl-Kyverno"
    uses: go/build
    with:
      modroot: kyverno
      packages: ./cmd/cli/kubectl-kyverno
      ldflags: |
        -s -X github.com/kyverno/kyverno/pkg/version.BuildVersion=${{package.version}}
        -X github.com/kyverno/kyverno/pkg/version.GitCommit={{.Commit}}
      output: kubectl-kyverno


  - name: "Build Cleanup-controller"
    uses: go/build
    with:
      modroot: kyverno
      packages: ./cmd/cleanup-controller
      deps: golang.org/x/crypto@v0.45.0
      ldflags: |
        -s -w -X github.com/kyverno/kyverno/pkg/version.BuildVersion=${{package.version}}
        -X github.com/kyverno/kyverno/pkg/version.GitCommit={{.Commit}}
      output: cleanup-controller



  - name: "Build Reports-controller"
    uses: go/build
    with:
      modroot: kyverno
      packages: ./cmd/reports-controller
      ldflags: |
        -s -w -X github.com/kyverno/kyverno/pkg/version.BuildVersion=${{package.version}}
        -X github.com/kyverno/kyverno/pkg/version.GitCommit={{.Commit}}
      output: reports-controller



  - name: "Build Background-controller"
    uses: go/build
    with:
      modroot: kyverno
      packages: ./cmd/background-controller
      ldflags: |
        -s -w -X github.com/kyverno/kyverno/pkg/version.BuildVersion=${{package.version}}
        -X github.com/kyverno/kyverno/pkg/version.GitCommit={{.Commit}}
      output: background-controller

  - uses: strip

  - name: "Cleanup"
    runs: |
      rm -rf kyverno
