# SPDX-FileCopyrightText: 2025 EvoCloud, Inc.
# SPDX-License-Identifier: MPL-2.0
#
# Source: https://github.com/spiffe/spire
# Reference: https://github.com/spiffe/spire/blob/main/Makefile
package:
  name: spire-agent
  version: 1.13.3
  epoch: 1
  description: "The SPIRE Agent runs on nodes within a SPIRE deployment. It attests workloads, retrieves SPIFFE IDs and SVIDs from the SPIRE Server, and securely delivers identities to applications and services"
  target-architecture:
    - x86_64
    #- aarch64
  url: "https://spiffe.io/spire/"
  copyright:
    - attestation: |
        Created by the EvoCloud Engineering Team. 
        Copyright (C) 2025 EvoCloud, Inc.
      license: MPL-2.0

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle

vars:
  git_commit: "191c76b489656502ff946afb486b47b83a376e81"  

pipeline:
  - name: "Prepare extraction directory"
    runs: |
      mkdir -p spire-agent

  - name: "Download SPIRE source"
    uses: fetch
    with:
      uri: https://github.com/spiffe/spire/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha512: 80d1cae29c1cc499361dc77aca2533c4b4f8932e0e157ba70fd8747df0cce8e9a3a383c0da201e51f14cb9e8a61a06d137a4dd36f0395a712e404a30b21b10b2 
      directory: spire-agent
      delete: true

  - name: "Build SPIRE Agent"
    uses: go/build
    with:
      modroot: spire-agent
      packages: ./cmd/spire-agent
      # secfixes:
      #   1.13.3-r1:
      #     - GHSA-f6x5-jh6r-wrfv
      #     - GHSA-j5w8-q4qc-rx2x 
      #     - CVE-2025-58181
      #     - CVE-2025-47914 
      deps: golang.org/x/crypto@v0.45.0 
      ldflags: "-s -X github.com/spiffe/spire/pkg/common/version.gittag=${{package.version}} -X github.com/spiffe/spire/pkg/common/version.githash=${{vars.git_commit}}"
      output: spire-agent

  - uses: strip

  - name: "Cleanup"
    runs: |
      rm -rf spire-agent

