# SPDX-FileCopyrightText: 2026 EvoCloud, Inc.
# SPDX-License-Identifier: MPL-2.0

# Source: https://github.com/kube-green/kube-green
# Reference: https://github.com/kube-green/kube-green/blob/main/Makefile
# Schema: https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md

package:
  name: kube-green
  version: 0.7.1
  epoch: 0
  description: "A K8s operator to reduce CO2 footprint of your clusters"
  target-architecture:
    - x86_64
  copyright:
    - attestation: |
        Created by the EvoCloud Engineering Team.
        Copyright (C) 2026 EvoCloud, Inc.
      license: MPL-2.0
      paths:
        - "*"
  url: "https://github.com/kube-green/kube-green"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle

vars:
  git_commit: "eb4a805915c00300a5262c6fdb9fde99a6d96941"
 

pipeline:
  #https://github.com/chainguard-dev/melange/blob/main/pkg/build/pipelines/git-checkout.yaml
  - name: "DOWNLOADING KUBE-GREEN SOURCE CODE"
    uses: git-checkout
    with:
      repository: https://github.com/kube-green/kube-green
      expected-commit: ${{vars.git_commit}}
      tag: v${{package.version}}

      
  - name: "BUILD KUBE-GREEN BINARY" 
    uses: go/build 
    with: 
      modroot: .
      packages: ./cmd/main.go
      ldflags: -s
      output: kube-green

  - uses: strip

update:
  enabled: true
  github:
    identifier: kube-green/kube-green
    strip-prefix: v  