# SPDX-FileCopyrightText: 2026 EvoCloud, Inc.
# SPDX-License-Identifier: MPL-2.0

# Source: https://github.com/Azure/azure-storage-azcopy
# Reference: https://github.com/Azure/azure-storage-azcopy/blob/main/docker/build.sh
# Schema: https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md

package:
  name: azcopy
  version: 10.31.1
  epoch: 0
  description: "The new Azure Storage data transfer utility - AzCopy v10"
  target-architecture:
    - x86_64 #supported architectures: 386, amd64, arm/v6, arm/v7, arm64, ppc64le, s390x, x86_64, aarch64, and all that builds it for all of them
  copyright:
    - license: Apache-2.0
    - attestation: |
        Created by the EvoCloud Engineering Team. 
        Copyright (C) 2026 EvoCloud, Inc.
      license: MPL-2.0
      paths:
        - "*"
  url: "https://github.com/Azure/azure-storage-azcopy"


environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle

vars:
  git_commit: "be9820d06f6c92f7607c87b9eae170903032b116"

pipeline:
  #https://github.com/chainguard-dev/melange/blob/main/pkg/build/pipelines/git-checkout.yaml
  - name: "DOWNLOADING AZCOPY SOURCE CODE"
    uses: git-checkout
    with:
      repository: https://github.com/Azure/azure-storage-azcopy
      expected-commit: ${{vars.git_commit}}
      tag: v${{package.version}}

# Known vulnerabilities that we are not fixing
# glibc vulnerabilities
#secfixes:
# 10.31.1-r1:
# - CVE-2026-0861
# - CVE-2026-0915


  - name: "BUILD AZCOPY BINARY" 
    uses: go/build 
    with: 
      modroot: .
      packages: .
      ldflags: -s
      output: azcopy

  - uses: strip

update:
  enabled: true
  github:
    identifier: Azure/azure-storage-azcopy
    strip-prefix: v  