# SPDX-License-Identifier: Apache-2.0
# Source: https://github.com/opencost/opencost
# Reference: https://github.com/opencost/opencost/blob/develop/Makefile
# Schema: https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md

package:
  name: opencost
  version: 1.118.0  
  epoch: 1
  description: "OpenCost cost monitoring for Kubernetes"
  target-architecture:
    - x86_64
  copyright:
    - attestation: |
        Created by the EvoCloud Engineering Team.
        Copyright (C) 2025 EvoCloud, Inc.
      license: MPL-2.0
  url: "https://github.com/opencost/opencost"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle

vars:
  git_commit: "37e08c6365d0f086562d049633e7a19bd025369a"

pipeline:
  - name: "Prepare extraction directory"
    runs: |
      mkdir -p opencost

  - name: "Download OpenCost source"
    uses: fetch
    with:
      uri: https://github.com/opencost/opencost/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha512: 268af22b2aefa0ef2238fd3e7739fa2df8483768b9344cc84af448bc51648d942f93ccc9ca2a8f9659a060b147e395a4baad4fd1a146553ac6d280227131e9c3
      directory: opencost
      delete: true

  - name: "Build CostModel"
    uses: go/build
    with:
      modroot: opencost
      packages: ./cmd/costmodel
      # secfixes:
      #   0.11.1-r1:
      #     - GHSA-f6x5-jh6r-wrfv
      #     - GHSA-j5w8-q4qc-rx2x 
      deps: golang.org/x/crypto@v0.45.0
      ldflags: |
            -extldflags "-static" 
            -s 
            -X github.com/opencost/opencost/core/pkg/version.Version=${{package.version}} 
            -X github.com/opencost/opencost/core/pkg/version.GitCommit=S{{vars.git_commit}}
      output: opencost

  - uses: strip

  - name: "Cleanup"
    runs: |
      rm -rf opencost

