# SPDX-FileCopyrightText: 2025 EvoCloud, Inc.
# SPDX-License-Identifier: MPL-2.0
# Source: https://github.com/kubernetes-sigs/cluster-api-provider-aws
# Reference: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/.goreleaser.yaml
# Schema: https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md

package:
  name: clusterawsadm
  version: 2.10.0
  epoch: 1
  description: "Kubernetes Cluster API Provider AWS provides consistent deployment and day 2 operations of self-managed and EKS Kubernetes clusters on AWS."
  target-architecture:
    - x86_64
  copyright:
    - attestation: |
        Created by the EvoCloud Engineering Team.
        Copyright (C) 2025 EvoCloud, Inc.
      license: MPL-2.0
  url: "https://github.com/kubernetes-sigs/cluster-api-provider-aws"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle

vars:
  git_commit: "175074f222a2984ec569ab743fd352e6683b27cf"
  build_date: "2025-12-15T10:39:04Z"
  git_major: "2"
  git_minor: "10"

pipeline:
  #https://github.com/chainguard-dev/melange/blob/main/pkg/build/pipelines/git-checkout.yaml
  - name: "DOWNLOADING CLUSTER-API-PROVIDER-AWS-SOURCE CODE"
    uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/cluster-api-provider-aws
      expected-commit: ${{vars.git_commit}}
      tag: v${{package.version}}

  - name: "PATCHING GO MODULES"
    # secfixes:
    #   2.10.0-r1:
    #     - GHSA-j5w8-q4qc-rx2x
    #     - GHSA-f6x5-jh6r-wrfv
    #     - GHSA-hj57-j5cw-2mwp 
    runs: |
      go get golang.org/x/crypto@v0.45.0
      go mod tidy
      go mod vendor

  - name: "BUILD CLUSTERAWSADM BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./cmd/clusterawsadm
      ldflags: |
        -s 
        -X sigs.k8s.io/cluster-api-provider-aws/v2/version.gitMajor=${{vars.git_major}}
        -X sigs.k8s.io/cluster-api-provider-aws/v2/version.gitMinor=${{vars.git_minor}}
        -X sigs.k8s.io/cluster-api-provider-aws/v2/version.gitVersion=v${{package.version}}
        -X sigs.k8s.io/cluster-api-provider-aws/v2/version.gitCommit=${{vars.git_commit}}
        -X sigs.k8s.io/cluster-api-provider-aws/v2/version.gitTreeState=clean
        -X sigs.k8s.io/cluster-api-provider-aws/v2/version.buildDate=${{vars.build_date}}
      output: clusterawsadm

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/cluster-api-provider-aws
    strip-prefix: v