# SPDX-License-Identifier: Apache-2.0
# Source: https://github.com/kedacore/keda
# Reference: https://github.com/kedacore/keda/blob/main/Makefile
# Schema: https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md

package:
  name: keda
  version: 2.18.1
  epoch: 1
  description: "KEDA is a Kubernetes-based Event Driven Autoscaler. With KEDA, you can drive the scaling of any container in Kubernetes based on the number of events needing to be processed."
  target-architecture:
    - x86_64 #supported architectures: 386, amd64, arm/v6, arm/v7, arm64, ppc64le, s390x, x86_64, aarch64, and all that builds it for all of them
  copyright:
    - attestation: |
        Created by the EvoCloud Engineering Team. 
        Copyright (C) 2025 EvoCloud, Inc.
      license: MPL-2.0
      paths:
        - "*"
  url: "https://keda.sh/"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle
      #- busybox
      #- go
      #- git
      #- make

vars:
  git_commit: "3f590ba6027a67b2d6f79ece605061f6d201c54b"

pipeline:
  - name: "CREATING KEDA DIR"
    runs: |
      mkdir keda

  - name: "DOWNLOADING KEDA SOURCE"
    uses: fetch
    with:
      uri: https://github.com/kedacore/keda/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha512: 0f047af7438e9959f1b0b62fc30b128ea0b81dab759df62faccf68e1d56ab4a99c338ad8cb90bafd04f39ba511088b495dac19ef72f43e19e338022add6203c2
      directory: keda
      delete: true

  # secfixes:
  #   2.18.1-r1:
  #     - GHSA-f6x5-jh6r-wrfv
  - name: "PATCHING DO DEPENDENCIES"
    runs: |
      cd keda
      go get golang.org/x/crypto@v0.45.0
      go mod tidy
      go mod vendor

  - name: "BUILDING KEDA"
    uses: go/build
    with:
      modroot: keda
      packages: ./cmd/operator
      ldflags: "-s -X 'github.com/kedacore/keda/v2/version.Version=${{package.version}}' -X 'github.com/kedacore/keda/v2/version.GitCommit={{vars.git_commit}}'"
      output: keda

  - uses: strip

  - name: "REMOVING DETRITUS"
    runs: |
      rm -rf keda

update:
  enabled: true
  github:
    identifier: kedacore/keda
    strip-prefix: v
    use-tag: true
