#SPDX-FileCopyrightText: 2025 EvoCloud, Inc.
# SPDX-License-Identifier: MPL-2.0
#
#Source:
#Ref: https://github.com/chainguard-dev/apko/blob/main/examples/nginx.yaml
#Schema: https://github.com/chainguard-dev/apko/blob/51830a2e043ace2da4eba4265083b2e3298437a8/pkg/build/types/schema.json

contents:
  repositories:
    - https://packages.wolfi.dev/os
    - '@local /work/packages'
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    - ./melange.rsa.pub
  packages:
    - keda-admission-webhooks@local

annotations:
  org.opencontainers.image.authors: EvoCloud Engineering Team <maintainers@evocloud.dev>
  org.opencontainers.image.title: Keda-webhooks (Packaged by EvoCloud)
  org.opencontainers.image.description: Distroless and near CVE free Keda-admission-webhooks OCI image
  org.opencontainers.image.source: https://github.com/kedacore/keda
  org.opencontainers.image.licenses: Apache-2.0
  org.opencontainers.image.vendor: EvoCloud
  org.opencontainers.image.version: "2.18.1"

accounts:
  groups:
    - groupname: nonroot
      gid: 65510
      members: []
  users:
    - username: nonroot
      uid: 65510
      shell: /bin/false
      #homedir: /dev/null
  run-as: nonroot

environment:
  PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin

entrypoint:
  type: ""
  command: /usr/bin/keda-admission-webhooks
  shell-fragment: ""
  services: {}
 

archs:
  - amd64
