# SPDX-FileCopyrightText: 2026 EvoCloud, Inc.
# SPDX-License-Identifier: MPL-2.0

# Source: https://github.com/pulumi/pulumi-kubernetes-operator
# Reference: https://github.com/pulumi/pulumi-kubernetes-operator/blob/master/Makefile
# Schema: https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md


package:
  name: pulumi-kubernetes-operator
  version: 2.3.0
  epoch: 1
  description: "A Kubernetes Operator that automates the deployment of Pulumi Stacks."
  target-architecture:
    - x86_64 #supported architectures: 386, amd64, arm/v6, arm/v7, arm64, ppc64le, s390x, x86_64, aarch64, and all that builds it for all of them
  copyright:
    - license: Apache-2.0
    - attestation: |
        Created by the EvoCloud Engineering Team. 
        Copyright (C) 2026 EvoCloud, Inc.
      license: MPL-2.0
      paths:
        - "*"
  url: "https://github.com/pulumi/pulumi-kubernetes-operator"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle

vars:
  git_commit: "2b7d86bf3d09c5defbc02bc096bb0ce7d08eee44"

pipeline:
  #https://github.com/chainguard-dev/melange/blob/main/pkg/build/pipelines/git-checkout.yaml
  - name: "DOWNLOADING PULUMI-KUBERNETES-OPERATOR SOURCE CODE"
    uses: git-checkout
    with:
      repository: https://github.com/pulumi/pulumi-kubernetes-operator
      expected-commit: ${{vars.git_commit}}
      tag: v${{package.version}}

  - name: "PATCHING GO MODULES"
    # secfixes:
    #   2.3.0-r1:
    #     - GHSA-j5w8-q4qc-rx2x
    #     - GHSA-f6x5-jh6r-wrfv
    #     - GHSA-r6j8-c6r2-37rr
    runs: |
      go get golang.org/x/crypto@v0.45.0
      go mod tidy
      go mod vendor


  - name: "BUILD OPERATOR BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./operator/cmd
      ldflags: |
        -s 
        -X github.com/pulumi/pulumi-kubernetes-operator/v2/operator/version.Version=${{package.version}}
      output: pulumi-kubernetes-operator

  - uses: strip

update:
  enabled: true
  github:
    identifier: pulumi/pulumi-kubernetes-operator
    strip-prefix: v
